export const compulsoryOrNot = [
  // This is a list of all the subjects in the BSE program.

  // Compulsory subjects
  { code: "FDE3023", status: "compulsory" },
  { code: "EEX3467", status: "compulsory" },
  { code: "EEI3346", status: "compulsory" },
  { code: "EEI3266", status: "compulsory" },
  { code: "EEX3373", status: "compulsory" },
  { code: "MHZ3459", status: "compulsory" },
  { code: "EEI3262", status: "compulsory" },
  { code: "EEI4346", status: "compulsory" },
  { code: "AGM3263", status: "compulsory" },
  { code: "EEI4267", status: "compulsory" },
  { code: "EEI4362", status: "compulsory" },
  { code: "EEX4465", status: "compulsory" },
  { code: "MHZ4256", status: "compulsory" },
  { code: "EEI4361", status: "compulsory" },
  { code: "EEI4366", status: "compulsory" },
  { code: "AGM4367", status: "compulsory" },
  { code: "EEY4189", status: "compulsory" },
  { code: "MHZ4377", status: "compulsory" },
  { code: "EEI5467", status: "compulsory" },
  { code: "EEI5270", status: "compulsory" },
  { code: "MHZ5375", status: "compulsory" },
  { code: "EEX5563", status: "compulsory" },
  { code: "EEW5811", status: "compulsory" },
  { code: "CVM5402", status: "compulsory" },
  { code: "EEX5362", status: "compulsory" },
  { code: "MHJ5372", status: "compulsory" },
  { code: "EEY6189", status: "compulsory" },
  { code: "DMM6602", status: "compulsory" },
  { code: "EEI6360", status: "compulsory" },
  { code: "EEI6171", status: "compulsory" },
  { code: "EEI6567", status: "compulsory" },
  { code: "EEM6202", status: "compulsory" },
  { code: "EEX6363", status: "compulsory" },
  { code: "EEY6689", status: "compulsory" },
  { code: "LTE34SI", status: "compulsory" },
  { code: "LTE34SE", status: "compulsory" },
  { code: "FDE3020", status: "compulsory" },
  { code: "LTE3401", status: "compulsory" },

  // Optional subjects
  { code: "MHZ2250", status: "optional" },
  { code: "LLJ3265", status: "optional" },
  { code: "EEM3366", status: "optional" },
  { code: "EEI4369", status: "optional" },
  { code: "EEX4373", status: "optional" },
  { code: "MHJ4271", status: "optional" },
  { code: "EEX5376", status: "optional" },
  { code: "EEI5280", status: "optional" },
  { code: "EEI5466", status: "optional" },
  { code: "EEX6340", status: "optional" },
  { code: "EEX6278", status: "optional" },
  { code: "ISI3376", status: "optional" },
  { code: "CSI3361", status: "optional" },
  { code: "EEX5464", status: "optional" }, // Will be compulsory from 2025/2026
  { code: "EEI3269", status: "optional" }, // Will be compulsory from 2025/2026
  { code: "EEI3372", status: "optional" }, // Will be compulsory from 2025/2026
];
